version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samroles-eh"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bc9iel2dapz1"
s3_prefix = "samroles-eh"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppSAMTemplateFile=\"app.template.yml\" SelfRepoArn=\"arn:aws:codecommit:us-west-1:477886346812:cfn-test-lint-pipeline\" SelfRepo=\"cfn-test-lint-pipeline\" InfraRepoArn=\"arn:aws:codecommit:us-west-1:477886346812:intership-sam-template-demo\" InfraRepo=\"intership-sam-template-demo\" InfraRepoBranch=\"master\""
