version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam build --template-file ${SAM_TEMPLATE_FILE}
  post_build:
    commands:
      - sam deploy --s3-bucket ${BUCKET_NAME} --template-file ${SAM_TEMPLATE_FILE}

artifacts:
  files:
    - packaged-template.yml
