version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam package --template-file app.template.yml --s3-bucket ${BUCKET_NAME} --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
