version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfn-lint-pipeline-main"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bc9iel2dapz1"
s3_prefix = "cfn-lint-pipeline-main"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RoleStackName=\"cfn-lint-pipeline-roles\" StorageStackName=\"cfn-lint-pipeline-storage\" AppSAMTemplateFile=\"app.template.yml\" SelfRepo=\"cfn-test-lint-pipeline\" InfraRepo=\"intership-sam-template-demo\" InfraRepoBranch=\"master\""
confirm_changeset = true
