version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfn-lint-pipeline-main"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bc9iel2dapz1"
s3_prefix = "cfn-lint-pipeline-main"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AmplifyBaseUrl=\"https://master.d1rlpip4n90nte.amplifyapp.com\" AmplifyWebHook=\"https://webhooks.amplify.us-west-1.amazonaws.com/prod/webhooks?id=b5b18ac9-a322-45e5-982a-ab19cfee7287&token=T3rSBzIolNy46sGeR6W2UICWP27ovT1hKwfF0sZfg&operation=startbuild\" AppBaseStackName=\"intership-infra\" RoleStackName=\"cfn-lint-pipeline-roles\" MessagingStackName=\"cfn-lint-pipeline-messaging\" StorageStackName=\"cfn-lint-pipeline-storage\" ServerlessStackName=\"cfn-lint-pipeline-serverless\" AppSAMTemplateFile=\"app.template.yml\" SelfRepo=\"cfn-test-lint-pipeline\" InfraRepo=\"intership-sam-template-demo\" InfraRepoBranch=\"master\""
