version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfn-lint-pipeline-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bc9iel2dapz1"
s3_prefix = "cfn-lint-pipeline-serverless"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MessagingStackName=\"cfn-lint-pipeline-messaging\" AmplifyWebHook=\"https://webhooks.amplify.us-west-1.amazonaws.com/prod/webhooks?id=b5b18ac9-a322-45e5-982a-ab19cfee7287&token=T3rSBzIolNy46sGeR6W2UICWP27ovT1hKwfF0sZfg&operation=startbuild\""
