---
AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline with CodeBuild workflow to run TaskCat ,  cfn-lint , cfn-nag
Transform: AWS::Serverless-2016-10-31

Parameters:
  MessagingStackName:
    Type: String
    Description: location of the sam file to test and deploy
    Default: cfn-lint-pipeline-messaging

  PipelineStackName:
    Type: String
    Description: location of the sam file to test and deploy
    Default: cfn-lint-pipeline-main

  StorageStackName:
    Type: String
    Description: location of the sam file to test and deploy
    Default: cfn-lint-pipeline-storage

Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 100

Resources:
  ########## Serverless Stuff
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: "ts-dependencies"
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain

  ## lambdas
  SNSPayloadLogger:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: nodejs14.x
      Handler: dist/mail/approve-mail.handler
      Events:
        StageTopicEvent:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: !Sub "${MessagingStackName}-StageNotificationSNSTopicArn"
        ProdopicEvent:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: !Sub "${MessagingStackName}-ProdNotificationSNSTopicArn"

      Policies:
        - AWSLambdaBasicExecutionRole

  InsertBuildResult:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Environment:
        Variables:
          TABLE_NAME:
            Fn::ImportValue: !Sub "${StorageStackName}-LintingTableID"
          BUCKET_NAME:
            Fn::ImportValue: !Sub "${StorageStackName}-LintingBucketID"

      Runtime: nodejs14.x
      Handler: dist/database/addPipelineResult.handler
      Events:
        PipelineLineUploadEventBridge:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - CodePipeline Stage Execution State Change
              detail:
                state:
                  - SUCCEEDED
                stage:
                  - UploadLintingResult
              resources:
                - Fn::ImportValue: !Sub "${PipelineStackName}-PipelineArn"
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue: !Sub "${StorageStackName}-LintingBucketID"
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue: !Sub "${StorageStackName}-LintingTableID"
