---
AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline with CodeBuild workflow to run TaskCat ,  cfn-lint , cfn-nag
Transform: AWS::Serverless-2016-10-31

Resources:
  CodeBucket:
    Type: AWS::S3::Bucket

  LintingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  LintingBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref LintingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${LintingBucket.Arn}/*"

  LintingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: executionID
        Type: String

  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

Outputs:
  LintingWebsite:
    Value: !GetAtt LintingBucket.WebsiteURL

  LintingTableID:
    Value: !Ref LintingTable
    Export:
      Name: !Sub "${AWS::StackName}-LintingTableID"

  CodeBucketID:
    Value: !Ref CodeBucket
    Description: "CodeBucket"
    Export:
      Name: !Sub "${AWS::StackName}-CodeBucketID"

  LintingBucketID:
    Value: !Ref LintingBucket
    Description: "LintingBucket"
    Export:
      Name: !Sub "${AWS::StackName}-LintingBucketID"

  PipelineArtifactBucketID:
    Value: !Ref PipelineArtifactBucket
    Description: "PipelineArtifactBucket"
    Export:
      Name: !Sub "${AWS::StackName}-PipelineArtifactBucketID"
