version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam validate --template-file ${CODEBUILD_SRC_DIR_ProjectSourceCode}/${SAM_TEMPLATE_FILE}
      - sam build --template-file ${CODEBUILD_SRC_DIR_ProjectSourceCode}/${SAM_TEMPLATE_FILE}
  post_build:
    commands:
      - sam deploy --template-file ${CODEBUILD_SRC_DIR_ProjectSourceCode}/${SAM_TEMPLATE_FILE} --no-fail-on-empty-changeset --stack-name="${APP_BASE_STACK_NAME}-${SAM_ENV}" --parameter-overrides="EnvType=${SAM_ENV}"
