version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam validate --template-file ${SAM_TEMPLATE_FILE}
      - sam build --template-file ${SAM_TEMPLATE_FILE}
  post_build:
    commands:
      - sam deploy --template-file ${SAM_TEMPLATE_FILE} --no-fail-on-empty-changeset
