version: 0.2
phases:
  install:
    commands:
      - echo install phase started on `date`
      - ruby --version
  build:
    commands:
      - echo Linting started on `date`
      - cfn_nag_scan --input-path $CODEBUILD_SRC_DIR_PackagingArtifacts/${SAM_TEMPLATE_FILE} -o json > nag.json
      - cat nag.json
  post_build:
    commands:
      - echo Linting completed on `date`

artifacts:
  files:
    - "nag.json"
