version: 0.2
phases:
  install:
    commands:
      - echo install phase started on `date`
      - python --version
  build:
    commands:
      - echo Linting started on `date`
      - mkdir output
      - cfn-lint ${SAM_TEMPLATE_FILE} > output/lint.txt
      - cat output/lint.txt
  post_build:
    commands:
      - echo Linting completed on `date`

artifacts:
  files:
    - "output/*"
