version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo install phase started on `date`
      - ruby --version
      - gem install cfn-nag
  build:
    commands:
      - echo Linting started on `date`
      # - TODO save warnings in s3 bucket
      - cfn_nag_scan --input-path ${SAM_TEMPLATE_FILE} > nag.txt
      - cat nag.txt
  post_build:
    commands:
      - echo Linting completed on `date`
      - aws s3 cp --acl public-read ./nag.txt s3://${BUCKET_NAME}/
