version: 0.2
phases:
  install:
    commands:
      - echo install phase started on `date`
      - python --version
  build:
    commands:
      - echo Linting started on `date`
      - cfn-lint $CODEBUILD_SRC_DIR_PackagingArtifacts/${SAM_TEMPLATE_FILE} --output-file lint.txt
      - cat lint.txt
  post_build:
    commands:
      - echo Linting completed on `date`

artifacts:
  files:
    - "lint.txt"
