version: 0.2
phases:
  install:
    commands:
      - echo install phase started on `date`
      - ruby --version
  build:
    commands:
      - mkdir $Execution_ID
      - echo Linting started on `date`
      - cfn_nag_scan --input-path $CODEBUILD_SRC_DIR_PackagingArtifacts/${SAM_TEMPLATE_FILE} -o json > "${Execution_ID}/nag.json"
      - cat "${Execution_ID}/nag.json"
  post_build:
    commands:
      - echo Linting completed on `date`

artifacts:
  files:
    - $Execution_ID/**/*
