version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo install phase started on `date`
      - ruby --version
      - gem install cfn-nag
  build:
    commands:
      - echo Linting started on `date`
      - cfn_nag_scan --input-path ${SAM_TEMPLATE_FILE}
  post_build:
    commands:
      - echo Linting completed on `date`
