version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo install phase started on `date`
      - node --version
  build:
    commands:
      - echo $Release_ID

artifacts:
  discard-paths: yes
  files:
    - output/${SAM_TEMPLATE_FILE}
