version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo install phase started on `date`
      - cd $CODEBUILD_SRC_DIR_FrontEndSourceCode && yarn install
  build:
    commands:
      - echo $Release_ID
      - pwd
      - cd $CODEBUILD_SRC_DIR_FrontEndSourceCode && yarn static
      - pwd
      - mv  $CODEBUILD_SRC_DIR_FrontEndSourceCode/out dist
      - ls -R

artifacts:
  files:
    - dist/**/*
