version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo install phase started on `date`
      - cd $CODEBUILD_SRC_DIR_FrontEndSourceCode && yarn install
  build:
    commands:
      - echo $Release_ID
      - OLD=`pwd`
      - cd $CODEBUILD_SRC_DIR_FrontEndSourceCode && yarn static

artifacts:
  files:
    - out/**/*
  base-directory: $CODEBUILD_SRC_DIR_FrontEndSourceCode
