version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo install phase started on `date`
      - yarn install
  build:
    commands:
      - echo $Release_ID
      - yarn static

artifacts:
  files:
    - out/**/*
