version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install phase started on `date`
  build:
    commands:
      - echo $Release_ID
      - echo Build phase started on `date`
      - mkdir output
      - sam package --s3-bucket ${BUCKET_NAME} --template-file ${CODEBUILD_SRC_DIR_ProjectSourceCode}/${SAM_TEMPLATE_FILE} > output/${SAM_TEMPLATE_FILE}

artifacts:
  discard-paths: yes
  files:
    - output/${SAM_TEMPLATE_FILE}
