version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install phase started on `date`
      - python --version
      - "curl -O https://bootstrap.pypa.io/get-pip.py"
      - python3 get-pip.py
      - pip3 install taskcat
  build:
    commands:
      - echo Build phase started on `date`
      - taskcat test run
      - aws s3 cp --recursive --acl public-read ./taskcat_outputs s3://${BUCKET_NAME}/

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - ./index.html
