---
AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline with CodeBuild workflow to run TaskCat ,  cfn-lint , cfn-nag
Transform: AWS::Serverless-2016-10-31

Parameters:
  # PipelineStackName:
  #   Type: String
  #   Default: cfn-lint-pipeline-main
  EnvType:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

Conditions:
  CreateDevResource: !Equals [!Ref EnvType, Dev]

Resources:
  StageNotificationSNSTopic:
    Type: AWS::SNS::Topic

  ProdNotificationSNSTopic:
    Type: AWS::SNS::Topic

  FinalSNSTopic:
    Type: AWS::SNS::Topic

  # CodePipelineFinishRule:
  #   Type: "AWS::Events::Rule"
  #   Properties:
  #     EventPattern:
  #       source:
  #         - aws.codepipeline
  #       detail-type:
  #         - CodePipeline Pipeline Execution State Change
  #       detail:
  #         state:
  #           - SUCCEEDED
  #           - FAILED
  #       resources:
  #         - Fn::ImportValue: !Join ["-", [!Ref PipelineStackName, PipelineArn]]
  #     State: ENABLED

  #     Targets:
  #       - Arn: !Ref FinalSNSTopic
  #         Id: "OpsTopic"

  EventTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: "sns:Publish"
            Resource: "*"
      Topics:
        - !Ref FinalSNSTopic

  EmailVerification:
    Condition: CreateDevResource
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref FinalSNSTopic
      Endpoint: wadhah.mahroug15@gmail.com
      Protocol: email

  EmailStageVerification:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref StageNotificationSNSTopic
      Endpoint: wadhah.mahroug15@gmail.com
      Protocol: email

Outputs:
  # resource IDS
  FinalSNSTopicID:
    Value: !Ref FinalSNSTopic
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", FinalSNSTopic]]

  StageNotificationSNSTopicID:
    Value: !Ref StageNotificationSNSTopic
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", StageNotificationSNSTopic]]

  ProdNotificationSNSTopicID:
    Value: !Ref ProdNotificationSNSTopic
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", ProdNotificationSNSTopic]]

  # ARNs
  FinalSNSTopicArn:
    Value: !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${FinalSNSTopic}"
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", FinalSNSTopicArn]]

  StageNotificationSNSTopicArn:
    Value: !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${StageNotificationSNSTopic}"
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", StageNotificationSNSTopicArn]]

  ProdNotificationSNSTopicArn:
    Value: !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${ProdNotificationSNSTopic}"
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", ProdNotificationSNSTopicArn]]
