---
AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline with CodeBuild workflow to run TaskCat ,  cfn-lint , cfn-nag
Transform: AWS::Serverless-2016-10-31

Parameters:
  # PipelineStackName:
  #   Type: String
  #   Default: cfn-lint-pipeline-main
  EnvType:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

Conditions:
  CreateDevResource: !Equals [!Ref EnvType, Dev]

Resources:
  StageNotificationSNSTopic:
    Type: AWS::SNS::Topic

  ProdNotificationSNSTopic:
    Type: AWS::SNS::Topic

  FinalSNSTopic:
    Type: AWS::SNS::Topic

  # CodePipelineFinishRule:
  #   Type: "AWS::Events::Rule"
  #   Properties:
  #     EventPattern:
  #       source:
  #         - aws.codepipeline
  #       detail-type:
  #         - CodePipeline Pipeline Execution State Change
  #       detail:
  #         state:
  #           - SUCCEEDED
  #           - FAILED
  #       resources:
  #         - Fn::ImportValue: !Join ["-", [!Ref PipelineStackName, PipelineArn]]
  #     State: ENABLED

  #     Targets:
  #       - Arn: !Ref FinalSNSTopic
  #         Id: "OpsTopic"

  EventTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: "sns:Publish"
            Resource: "*"
      Topics:
        - !Ref FinalSNSTopic

  EmailVerification:
    Condition: CreateDevResource
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref FinalSNSTopic
      Endpoint: wadhah.mahroug15@gmail.com
      Protocol: email

  EmailStageVerification:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref StageNotificationSNSTopic
      Endpoint: wadhah.mahroug15@gmail.com
      Protocol: email

  # ApproveByDevPolicy:
  #   Type: "AWS::IAM::Policy"
  #   Properties:
  #     Users: []
  #     PolicyName: CFNUsers
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Action:
  #             - codepipeline:ListPipelines
  #           Resource:
  #             - "*"
  #           Effect: Allow
  #         - Action:
  #             - codepipeline:GetPipeline
  #             - codepipeline:GetPipelineState
  #             - codepipeline:GetPipelineExecution
  #           Effect: Allow
  #           Resource: arn:aws:codepipeline:us-east-2:80398EXAMPLE:MyFirstPipeline
  #         - Action:
  #             - codepipeline:PutApprovalResult
  #           Effect: Allow
  #           Resource: arn:aws:codepipeline:us-east-2:80398EXAMPLE:MyFirstPipeline/MyApprovalStage/MyApprovalAction
  # ApproveByOwnerPolicy:
  #   Type: "AWS::IAM::Policy"
  #   Properties:
  #     Users: []
  #     PolicyName: CFNUsers
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Action:
  #             - codepipeline:ListPipelines
  #           Resource:
  #             - "*"
  #           Effect: Allow
  #         - Action:
  #             - codepipeline:GetPipeline
  #             - codepipeline:GetPipelineState
  #             - codepipeline:GetPipelineExecution
  #           Effect: Allow
  #           Resource: arn:aws:codepipeline:us-east-2:80398EXAMPLE:MyFirstPipeline
  #         - Action:
  #             - codepipeline:PutApprovalResult
  #           Effect: Allow
  #           Resource: arn:aws:codepipeline:us-east-2:80398EXAMPLE:MyFirstPipeline/MyApprovalStage/MyApprovalAction

Outputs:
  # resource ARNs
  FinalSNSTopicArn:
    Value: !Ref FinalSNSTopic
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", FinalSNSTopicArn]]

  StageNotificationSNSTopicArn:
    Value: !Ref StageNotificationSNSTopic
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", StageNotificationSNSTopicArn]]

  ProdNotificationSNSTopicArn:
    Value: !Ref ProdNotificationSNSTopic
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", ProdNotificationSNSTopicArn]]
