---
AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline with CodeBuild workflow to run TaskCat ,  cfn-lint , cfn-nag
Transform: AWS::Serverless-2016-10-31

Parameters:
  PipelineStackName:
    Type: String
    Default: cfn-lint-pipeline-main
  EnvType:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

Conditions:
  CreateDevResource: !Equals [!Ref EnvType, Dev]

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "cfntopic"

  CodePipelineFinishRule:
    Type: "AWS::Events::Rule"
    Properties:
      EventPattern:
        source:
          - aws.codepipeline
        detail-type:
          - CodePipeline Stage Execution State Change
        # detail:
        #   state:
        #     - SUCCEEDED
        #     - FAILED
        resources:
          - Fn::ImportValue: !Join ["-", [!Ref PipelineStackName, PipelineID]]
      State: ENABLED

      Targets:
        - Arn: !Ref MySNSTopic
          Id: "OpsTopic"

  EventTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: "sns:Publish"
            Resource: "*"
      Topics:
        - !Ref MySNSTopic

  EmailVerification:
    Condition: CreateDevResource
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref MySNSTopic
      Endpoint: wadhah.mahroug15@gmail.com
      Protocol: email

Outputs:
  SNSTopicID:
    Value: !Ref MySNSTopic
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", SNSTopicID]]
